POST http://localhost:3001/api/patients/
Content-Type: application/json

{
  "name": "Herra Kipeä",
  "dateOfBirth": "1971-04-09",
  "ssn": "090471-1234",
  "gender": "male",
  "occupation": "Digital dude",
  "entries": []
}