POST http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "date": "2023-08-05",
  "specialist": "Dr. Eemeli",
  "type": "HealthCheck",
  "description": "Digital OD.",
  "healthCheckRating": 0
}
