services:
  app:
    image: todo-frontend
    build:
      context: ./todo-frontend/
      dockerfile: ./Dockerfile
    volumes:
      - ./todo-frontend:/usr/src/app
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080/api
    container_name: todo-front-prod

  server:
    image: todo-backend
    volumes:
      - ./todo-backend:/usr/src/app
    build:
      context: ./todo-backend/
      dockerfile: ./Dockerfile
    environment:
      - REDIS_URL=//redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
    container_name: todo-back-prod

  mongo:
    image: mongo
    user: root
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    container_name: todo-mongo

  redis:
    image: redis
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./todo-backend/redis_data:/data
    container_name: todo-redis

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: todo-proxy
    depends_on:
      - app
      - server

volumes:
  mongo_data:
