DELETE http://localhost:3003/api/users/648578b721b0e586e1a42258
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRoaXJkdXNlciIsImlkIjoiNjQ4NTc4YjcyMWIwZTU4NmUxYTQyMjU4IiwiaWF0IjoxNjg2NTU5ODU0fQ.jRKbE67_KBLOn3L1O8Z46Mmxfne3PQqG2pQFcqcc4DI