DELETE http://localhost:3003/api/blogs/6486d303864fae1230e03bac
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRoaXJkdXNlciIsImlkIjoiNjQ4NTc4YjcyMWIwZTU4NmUxYTQyMjU4IiwiaWF0IjoxNjg2NTAyMDIwfQ.K5kfDBXbYNayDCEfLQ-3Ld2a3pipvbHl1ailcJ4B0Lo