DELETE http://localhost:3001/api/blogs/3
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtyaXN0aWFuLmhhbm51bGFAcHJvdG9uLm1lIiwiaWQiOjEsImlhdCI6MTY5OTgxMTg0OH0.FDw6c3lmFB2j7oU54B0H4i2_QnUSlaKG0T5WuUzDzeA
