# fly.toml app configuration file generated for bloglist-postgres-khannula on 2023-09-29T13:23:48+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bloglist-postgres-khannula"
primary_region = "arn"

[build]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
